#! /bin/sh
xrandr --output DP-1 --left-of HDMI-1

xrandr --output DP-2 --rotate left
xrandr --output DP-2 --right-of HDMI-1

/home/aditya/.config/bspwm/layout.sh

bspc monitor HDMI-1 -d 1 2 3 4 5
bspc monitor DP-1 -d 6 7
bspc monitor DP-2 -d 8 9 10
bspc wm -O HDMI-1 DP-1 DP-2

bspc config border_width         2
bspc config window_gap           4
bspc config top_padding         24
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill /home/aditya/.config/tiles.jpg
bash /home/aditya/.config/polybar.sh & disown
xcompmgr & disown
dunst & disown
flameshot & disown
